blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.landing, name='blog-landing'),
    path('', views.home, name ='blog-home'),
    path('about/', views.about, name='blog-about'),
]

courses/urls.py
from django.urls import path
from django.conf.urls import url, include
from courses import views

urlpatterns = [
    path('course-landing/', views.course_view, name='course-landing'),
    path('course-create/',views.create_course, name='course-create'),
    path('my-courses/',views.my_course, name='my-course'),
    url(r'modify-course/(?P<course_pk>\d+)/$', views.create_lesson, name='modify-course'),
    url(r'courses/(?P<subject>[\w|\W]+)/$', views.view_courses, name='view-courses'),
    url(r'course/(?P<course_pk>[\w|\W]+)/$', views.view_specific_course, name='view-this-course'),
    url(r'^publish/(?P<course_pk>\d+)/(?P<pub>[\w|\W]+)/$', views.publish_check, name="publish"),
    url(r'^delete/(?P<course_pk>\d+)/$', views.delete_course, name="delete-course")
   

    
]

django_project/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib import admin
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static
from quiz import views as quiz_views
from courses import views

urlpatterns = [
    url('admin/', admin.site.urls),
    url('register/', user_views.register, name ='register'),
    url('', include('dashboard.urls')),
    url('quiz', include('quiz.urls')),
    url('profile/', user_views.profile, name ='profile'),
    url('login/', auth_views.LoginView.as_view(template_name = 'users/login.html'), name ='login'),
    url('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name ='logout'),
    url('', include('blog.urls')),
    url('', include('stats.urls')),
    url('', include('quiz.urls')),
    url('', include('courses.urls')),    
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    

courses/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

# The Application has Courses. Courses are made up of one or more Lessons
class Course(models.Model):
    SUBJECT_CHOICE = (
                      ("Computing", "Computing"),
                      ("English", "English"),
                      ("Geography", "Geography"),
                      ("Chemistry", "Chemistry"),
                      ("Physics", "Physics"),
                      ("Music", "Music"),
                      ("Art", "Art"),
                      ("History", "History"), 
                    )

    name = models.CharField(max_length = 45)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    description = models.CharField(max_length=250)
    subject = models.CharField(max_length=15, choices=SUBJECT_CHOICE,default="Computing")
    published = models.BooleanField(default=False)
    slug = models.SlugField(default=name)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return self.course.get_absolute_url()

    class Meta:
        verbose_name_plural = "Course"

class Lesson(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    lesson = models.IntegerField(default=1)
    all_the_content = models.CharField(max_length=1500)
    additional_content_1 = models.CharField(max_length=1500, blank=True, default='', null=True)
    additional_content_2 = models.CharField(max_length=1500, blank=True, default='', null=True)
    file_upload = models.FileField(null=True, blank=True)
    file_upload_1 = models.FileField(null=True, blank=True)
    file_upload_2 = models.FileField(null=True, blank=True)
    file_upload_3 = models.FileField(null=True, blank=True)

    def __str__(self):
        return self.course.name

    class Meta:
        verbose_name_plural = "Lesson"

courses/forms.py
from django import forms
from django.utils.html import strip_tags
from .models import Lesson, Course
from django_bleach.forms import BleachField

class CreateCourseForm(forms.ModelForm):
    name = forms.CharField(label="Course Title", max_length = 45)
    description = BleachField(label= "Course Description", max_length=2500)
    subject = forms.ChoiceField(choices= Course.SUBJECT_CHOICE)
    class Meta:
        model = Course
        fields = ['name','subject']

class CreateLessonForm(forms.ModelForm):
    all_the_content = BleachField(label="Course Content", max_length=1500)
    additional_content_1 = BleachField(label="additonal content 1", max_length=1500,required=False)
    additional_content_2 = BleachField(label="additonal content2", max_length=1500,required=False)
    file_upload = forms.FileField(required=False)
    file_upload_1 = forms.FileField(required=False)
    file_upload_2 = forms.FileField(required=False)
    file_upload_3 = forms.FileField(required=False)

    class Meta:
        model = Lesson
        fields = ['all_the_content','additional_content_1','additional_content_2','file_upload']

courses/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from courses.models import Course, Lesson
from courses.forms import CreateCourseForm, CreateLessonForm
from django.http import HttpResponse, HttpResponseRedirect
# Create your views here.

@login_required
def course_view(request):
    re = Course.SUBJECT_CHOICE
    user_name = request.user

    my_courses = Course.objects.filter(user=user_name)
    args ={
        "subjects": re,
        "my_published": my_courses
    }
    return render(request, 'courses/course_home.html', args)

@login_required
def my_course(request):
    user = request.user
    all_my_course = Course.objects.filter(user=user)
    args ={
        "my_courses": all_my_course
    }
    return render(request, 'courses/my_courses.html', args)

@login_required
def view_specific_course(request, course_pk):
    get_all_lessons = Lesson.objects.filter(course=course_pk)
    course_name = Course.objects.filter(pk=course_pk)
    args ={
        "all_lessons": get_all_lessons,
        "name": course_name 
    }

    return render(request, 'courses/course_view.html', args)

@login_required
def create_course(request):
    user = request.user
    create_form = CreateCourseForm(request.POST)
    if request.method == "POST":
        if create_form.is_valid():
            name = create_form.cleaned_data.get('name')
            description = create_form.cleaned_data.get('description')
            subject = create_form.cleaned_data.get('subject')
            instance = create_form.save(commit=False)
            instance.name = name
            instance.description = description
            instance.subject = subject
            instance.user = user
            instance.slug = (subject + "-Course")
            instance.save()
            return HttpResponseRedirect('/my-courses')
   
    args  ={
        "form": create_form
    }

    return render(request, 'courses/course_create.html', args)

@login_required
def view_courses(request, subject):
    courses = Course.objects.filter(subject=subject)

    args  ={"all_courses": courses,
            "subject": subject}
    return render(request, 'courses/all_courses.html', args)
    

@login_required
def create_lesson(request, course_pk):
    session = request.session.get('course_session')
    form = CreateLessonForm(request.POST)
    pk = Course.objects.filter(pk=course_pk).first()
    count = Lesson.objects.filter(course=pk).count()
    count= count+1
    print(count)
    args  = { "form": form,
              "Course": pk,
              "lesson_count": count }

    if request.method == "POST":
        if form.is_valid():
            course = session
            all_the_content= form.cleaned_data.get('all_the_content')
            additional_1 = form.cleaned_data.get('additional_content_1')
            additional_2 =form.cleaned_data.get('additional_content_2')
            instance = form.save(commit=False)
            instance.course = pk
            instance.all_the_content = all_the_content
            instance.additional_content_1 = additional_1
            instance.additional_content_2 = additional_2
            instance.file_upload = form.cleaned_data.get('file_upload')
            instance.lesson = count
            instance.save()
            #del request.session['course_session']
            return HttpResponseRedirect(request.path_info)


    return render(request, 'courses/lesson_create.html', args)

@login_required
def publish_check(request, course_pk, pub):
    checked = pub
    course = Course.objects.get(id=course_pk)
    course.published = pub
    course.save()
    return HttpResponseRedirect('/my-courses')


@login_required
def delete_course(request, course_pk):
    course = Course.objects.filter(id=course_pk).delete()
    return HttpResponseRedirect('/my-courses')
        

    

courses/templates/courses/all_courses.html
{% extends "dashboard/base.html" %}

{% block content %}

<div class="row justify-content-center">
    <div class="col-4">
        <h1 class="text-center mod-title">{{subject}} Courses'</h1>
    </div>

</div>
<div class="row">

    {% for course in all_courses %}
    {% if course.published %}
    <div class="col-xs-4 mt-4 m-4">
        <div data-aos="flip-left" data-aos-easing="ease-out-cubic"
        data-aos-duration="2000" id="course-card"class="card" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title">{{course}}</h5>
              <h6 class="card-subtitle mb-2 text-muted">by: {{course.user}}</h6>
              <p class="card-text">{{course.description}}</p>
              <a href="{% url 'view-this-course' course_pk=course.pk %}" class="card-link mod-title text-center">View</a>

            </div>
          </div>
    </div>
    {% endif %}
    {% endfor %}

</div>



{% endblock content %}

courses/templates/courses/course_create.html
{% extends "dashboard/base.html" %}
{% block content %}
{% load crispy_forms_tags %}

<div class="row justify-content-center">
    <h2 class="mod-title mb-3 mt-3">Create Course</h2>
</div>
<div class="row justify-content-center">
    <div class="col-sm-8">
        <form method="POST" action="">
            {% csrf_token %}
            {{form|crispy}}
            <input class="btn btn-dark" type="submit" name="submit" value="submit">
        </form>
    </div>
</div>


{% endblock content %}

courses/templates/courses/course_home.html
{% extends "dashboard/base.html" %}


{% block content %}

<div class="row justify-content-center">
  <div class="col-8 mt-2 text-center">
      <legend class="text-center">Courses</legend>
      <p class="text-center text-muted">My Courses</p>
  </div><!--End of Column-->
</div><!--End of Row-->


<div class="row justify-content-center">

  <div class="col-sm-4 course-sect m-2">
    <legend class="text-center">Available Subjects</legend>

    {% for subjects in subjects %}
    <div id="subject-hover" class="subject-item text-center p-3"><a href="{% url 'view-courses' subject=subjects.0 %}">{{subjects.0}}</a></div>
    {% endfor %}

  </div>
  <div class="col-sm-4 course-sect m-2">
    <legend class="text-center">My Courses</legend>
    {% for courses in my_published %}
    <div id="subject-hover" class="subject-item text-center p-3"><a class="p-4"href="{% url 'view-this-course' course_pk=courses.id %}">{{courses}}</a></div>
    {% endfor %}
  </div>
</div>



{% endblock content %}

courses/templates/courses/course_view.html
{% extends "dashboard/base.html" %}


{% block content %}


<div class="row justify-content-center">
    {% for nm in name %}
    <h2 class="mod-title mb-3 mt-2">{{nm.name}}</h2>
    {% endfor %}
</div>
<div class="row justify-content-center">
    <div class="default-tabs mt-3">
        <ul class="nav nav-tabs default-tabs ">
            {% for lesson in all_lessons %}
            <li id="{{lesson.lesson}}" class="nav-link tabss"><a role="tab" data-toggle="tab" href="#lesson{{lesson.lesson}}">Lesson: {{lesson.lesson}} </a> </li>
            {% endfor %}
        </ul>
    </div>
</div>

<div class="row ">
    <div class="col-sm-4">
        <div class="course-sect mt-4">
            <h2 class="text-center mod-title">Course Resources</h2>
            <legend style="font-size: 15px !important;" class="text-muted text-center">(Available Downloadble Resources)</legend><hr style=" background-color: white !important;">
            {% for lesson in all_lessons %}
                {% if lesson.file_upload %}
                <a href="{{lesson.file_upload.url}}" download><p class="text-center mod-title">{{lesson.file_upload}} - Download</p></a>
                {% endif %}
            {% endfor %}

        </div>
    </div>
    
    
    <div class="col-sm-8 mt-4 check">
        <div class="tab-content">
            {% for lesson in all_lessons %}
            <div class="tab-pane text-center" id ="lesson{{lesson.lesson}}">
                <div class = "text-center mr-0 course-sect-main text-white ">
                    <h3 class="text-center mod-title">Lesson: {{lesson.lesson}}</h3>
                    <p class="wordwrap text-center">{{lesson.all_the_content}}</p>
                    <p class="wordwrap text-center">{{lesson.additional_content_1}}</p>
                    <p class="wordwrap text-center">{{lesson.additional_content_2}}</p>
                    {% if lesson.file_upload %}
                    

                    {% endif %}
                </div>
            </div>
        
            {% endfor %}
    
        </div>


    </div>
</div>

{% endblock content %}
{% block javascript %}
<script>
$(document).ready(function(){

    $('#lesson1').addClass("active");
    
    $('.tabss').on('click', function(){
        //alert($(this).attr("id"));
        ($(this).css("background-color", "gray"));
        
        
    });
    
    $('')



});

</script>



{% endblock javascript %}

courses/templates/courses/lesson_create.html
{% extends "dashboard/base.html" %}
{% block content %}
{% load crispy_forms_tags %}

<div class="row justify-content-center">
    <div class="col-8">
        <h1 class="text-center mod-title">Create Lesson</h1>
        <legend class="text-muted text-center">Course: {{Course}} by {{user}}</legend>
        <legend class="text-muted text-center">Current Lesson: {{lesson_count}}</legend>
        <legend class="text-muted text-center">Need more space? <input style="background-color: #FF4481 !important; color: white; " class="btn " type="button" id="add" name="" value="Add"></legend>
    </div>
</div>  
<div class="row justify-content-center">
    <div class="col-sm-8">
        <form id="frm" method="POST"action="">
            
            {% csrf_token %}
            {{form|crispy}}
            <input class="btn btn-dark" type="submit" name="submit" value="submit">
        </form>
    </div>
</div>

{% endblock content %}

{% block javascript %}
<script>
$(document).ready(function(){
    var newInputItem;
    var counter = 0;
    $('#div_id_additional_content_1').hide();
    $('#div_id_additional_content_2').hide();
  
    $('#add').on('click', function(){
        counter += 1;
                  
        if(counter == 2){
            $('#div_id_additional_content_2').show();
            //alert("YEHAW");
        }else{
            $('#div_id_additional_content_1').show();
            
        }
        
    });

    $('textarea').on("input", function(){
        var maxlength = 1500;
        var currentLength = $(this).val().length;
        console.log(currentLength);

        if(currentLength >=maxlength){
            $("label[for='id_all_the_content']").text("Max Characters Exeeded.");
            
        }else{ $("label[for='id_all_the_content']").text(currentLength + "/" + maxlength + " characters left"); }

    });
    





});

</script>



{% endblock javascript %}

courses/templates/courses/my_courses.html
{% extends "dashboard/base.html" %}

{% block content %}

<div class="row justify-content-center">
    <div class="col-4">
        <h1 class="text-center mod-title">My Courses</h1>
    </div>

</div>
<div class="row">

    {% for course in my_courses %}
    <div class="col-xs-4 mt-4 m-4">
        <div data-aos="flip-left" data-aos-easing="ease-out-cubic"
        data-aos-duration="2000" id="course-card"class="card" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title">{{course}}</h5>
              <h6 class="card-subtitle mb-2 text-muted">by: {{course.user}}</h6>
              <p class="card-text">{{course.description}}</p>
              <a href="{% url 'modify-course' course_pk=course.pk %}" class="card-link mod-title">Modify</a>
              <a href="{% url 'delete-course' course_pk=course.pk %}" class="card-link mod-title ml-1 mr-2">Delete</a>
              {% if course.published is True %}
                <p>Status: Published</p>
                <a href="{% url 'publish' course_pk=course.pk pub=False  %}" class="card-link mod-title">Make Private</a>
              {% else %}
              <p>Status: Private</p>
              <a href="{% url 'publish' course_pk=course.pk pub=True  %}" class="card-link mod-title">Make Public</a>
              {% endif %}
            
            </div>
          </div>
    </div>
    {% endfor %}
</div>

{% endblock content %}

{% block javascript %}


{% endblock javascript %}